### Create hash based short URL
POST http://localhost:8080/api/v1/url
Content-Type: application/json

{
  "url": "https://longurlgoeshere.com"
}

### Create counter based short URL
POST http://localhost:8080/api/v2/url
Content-Type: application/json

{
  "url": "https://very-long-url.com",
  "expiresAt": "2026-02-18T13:34:00Z"
}

### Short URL
# @no-redirect
GET http://localhost:8080/j9we
